version: '2'
services:
  mcowebsite-app:
    image: mcowebsite
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://mcowebsite-postgresql:5432/MCOWebsite
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://mcowebsite-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://mcowebsite-elasticsearch:9200
    ports:
      - 8080:8080
  mcowebsite-postgresql:
    extends:
      file: postgresql.yml
      service: mcowebsite-postgresql
  mcowebsite-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: mcowebsite-elasticsearch
